### ISSUE TITLE
Bug: when using vue filter with bracket will crash the formatter

### ISSUE THREAD

**Issue by vip30** [prettier/plugin-pug#115]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.6.1        |
| Prettier | v2.1.2        |
| Node     | v14.8.0      |
| OS       | win |

## Input

```pug
p.assignees-tooltip__time() Issue date: {{ issueDate | dateFormat("DD MMM YYYY") }}
```

## Output or Error

```bash
[PugPrinter:formatText]:  SyntaxError: Unexpected token '('
    at i (C:\Project\SCMP\collaborate-web\node_modules\prettier\parser-angular.js:46:16461)     
    at e.parseNgInterpolation (C:\Project\SCMP\collaborate-web\node_modules\prettier\parser-angular.js:46:17640)
    at s (C:\Project\SCMP\collaborate-web\node_modules\prettier\parser-angular.js:46:28364)     
    at Object.e.parseInterpolation (C:\Project\SCMP\collaborate-web\node_modules\prettier\parser-angular.js:46:28664)
    at C:\Project\SCMP\collaborate-web\node_modules\prettier\parser-angular.js:46:29282
    at Object.parse (C:\Project\SCMP\collaborate-web\node_modules\prettier\parser-angular.js:46:28970)
    at Object.parse (C:\Project\SCMP\collaborate-web\node_modules\prettier\index.js:13575:19)   
    at coreFormat (C:\Project\SCMP\collaborate-web\node_modules\prettier\index.js:14851:25)     
    at format (C:\Project\SCMP\collaborate-web\node_modules\prettier\index.js:15073:14)
    at formatWithCursor (C:\Project\SCMP\collaborate-web\node_modules\prettier\index.js:15090:12)
```

## Expected Output

```pug
p.assignees-tooltip__time() Issue date: {{ issueDate | dateFormat("DD MMM YYYY") }}
```

**Comment by Shinigami92** [comment]
@vip30 Is this `vue` or `angular`?

**Comment by Shinigami92** [comment]
Oh I found out it never crashed :smile:  
It was just a `warning`!

I changed/improved it to  
![image](https://user-images.githubusercontent.com/7195563/94339242-a4330200-fff8-11ea-9bb5-793dd6eb2420.png)
