### ISSUE TITLE
Bug: Interpolating Javascript codes creates a warn

### ISSUE THREAD

**Issue by SkyaTura** [prettier/plugin-pug#184]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.5                  |
| Prettier  | v2.x.x                  |
| Framework | vue |
| Node      | v14.15.3                  |
| OS        | mac           |

## Prettier config

```json
{}
```

## Input

```pug
p {{ new Date().toISOString() }}
```

## Output or Error

```bash
console.warn
    [PugPrinter:formatText]:  SyntaxError: Unexpected token 'Date'
        at o (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/parser-angular.js:46:17262)
        at Object.<anonymous>.e.parseNgInterpolation (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/parser-angular.js:46:18429)
        at s (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/parser-angular.js:46:29190)
        at Object.<anonymous>.e.parseInterpolation (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/parser-angular.js:46:29490)
        at /Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/parser-angular.js:46:30113
        at Object.parse (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/parser-angular.js:46:29796)
        at Object.parse (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/index.js:13625:19)
        at coreFormat (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/index.js:14899:14)
        at format (/Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/index.js:15131:14)
        at /Users/skyatura/projects/shinigami92/plugin-pug/node_modules/prettier/index.js:57542:12
```

**Comment by SkyaTura** [comment]
I'm trying to track the problem down, without any success yet...

**Comment by Shinigami92** [comment]
Try

```pug
- var date = new Date().toISOString()
p {{ date }}
```

**Comment by SkyaTura** [comment]
This would work, however, on vue, something like this should be valid to keep reactivity:
```pug
p {{ $moment(date).format('DD/MM/YYYY') }}
```

_I know that isn't pretty, but it's valid. I have some occurrences of this case older repositories_

**Comment by Shinigami92** [comment]
Are you willing to provide a PR for this fix?

I thing the warning is thrown somewhere here:
https://github.com/prettier/plugin-pug/blob/6b88a4fb2c49bb6dd321c9887b36574383097366/src/printer.ts#L407-L438

If you like you can try to find a better solution for this if-else mess :slightly_smiling_face:
