### ISSUE TITLE
Bug: Can't handle non-JS script content

### ISSUE THREAD

**Issue by OiYouYeahYou** [prettier/plugin-pug#244]
## Info

| Tool     | Version |
| -------- | ------- |
| Plugin   | v1.15.3 |
| Prettier | v2.3.2  |

## Prettier config

`default`

## Input

```pug
doctype html
html
	head
		script(type='application/ld+json').
			{
				"@context": "http://schema.org",
				"@type": "Website",
				"name": "Example",
				"headline": "Example of problem",
				"url": "https://example.com/"
			}

	body
		div Hello World
```

## Output or Error

```bash
test.pugSyntaxError: Unexpected token (2:12)
  1 | {
> 2 |   "@context": "http://schema.org",
    |             ^
  3 |   "@type": "Website",
  4 |   "name": "Example",
  5 |   "headline": "Example of problem",
    at ir (/home/jason/temp/pug-problem/node_modules/prettier/parser-babel.js:22:7277)
    at En (/home/jason/temp/pug-problem/node_modules/prettier/parser-babel.js:22:66392)
    at Object.parse (/home/jason/temp/pug-problem/node_modules/prettier/parser-babel.js:22:332006)
    at Object.parse$a [as parse] (/home/jason/temp/pug-problem/node_modules/prettier/index.js:13684:19)
    at coreFormat (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15215:16)
    at formatWithCursor$1 (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15455:14)
    at /home/jason/temp/pug-problem/node_modules/prettier/index.js:60228:12
    at Object.format (/home/jason/temp/pug-problem/node_modules/prettier/index.js:60248:12)
    at PugPrinter.start-pipeless-text (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/printer.js:1000:41)
    at PugPrinter.build (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/printer.js:100:54) {
  loc: { start: { line: 2, column: 12 } },
  codeFrame: '\u001b[0m \u001b[90m 1 |\u001b[39m {\u001b[0m\n' +
    '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 2 |\u001b[39m \t\u001b[32m"@context"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"http://schema.org"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m   |\u001b[39m \t          \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 3 |\u001b[39m \t\u001b[32m"@type"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"Website"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 4 |\u001b[39m \t\u001b[32m"name"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"Example"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 5 |\u001b[39m \t\u001b[32m"headline"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"Example of problem"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m'
}
[error] test.pug: Error: SyntaxError: Unexpected token (2:12)
[error]   1 | {
[error] > 2 |   "@context": "http://schema.org",
[error]     |             ^
[error]   3 |   "@type": "Website",
[error]   4 |   "name": "Example",
[error]   5 |   "headline": "Example of problem",
[error]     at PugPrinter.build (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/printer.js:106:23)
[error]     at Object.print (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/index.js:66:40)
[error]     at callPluginPrintFunction (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14958:21)
[error]     at mainPrintInternal (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14896:17)
[error]     at mainPrint (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14878:14)
[error]     at printAstToDoc (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14865:13)
[error]     at coreFormat (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15226:15)
[error]     at formatWithCursor$1 (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15455:14)
[error]     at Object.formatWithCursor (/home/jason/temp/pug-problem/node_modules/prettier/index.js:60228:12)
[error]     at format$1 (/home/jason/temp/pug-problem/node_modules/prettier/bin-prettier.js:16827:21)
```

## Expected Output

```pug
doctype html
html
	head
		script(type='application/ld+json').
			{
				"@context": "http://schema.org",
				"@type": "Website",
				"name": "Example",
				"headline": "Example of problem",
				"url": "https://example.com/"
			}

	body
		div Hello World
```

## Additional Context

I am assuming that the plugin assumes all scripts are JS, but this is annoying when you're not putting JS in a script tag. It can't be fixed with a `//- prettier-ignore` either, as it'll reformat the child content.

**Comment by Shinigami92** [comment]
I will have time upcoming weekend.
If you like you can try to create a PR

**Comment by Shinigami92** [comment]
Please try out the new beta [v1.16.0-0](https://www.npmjs.com/package/@prettier/plugin-pug/v/1.16.0-0) and report anything back :slightly_smiling_face:
