### ISSUE TITLE
AngularJS (1) one-time-binding not supported

### ISSUE THREAD

**Issue by toumas** [prettier/plugin-pug#77]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.1.8        |
| Prettier | v1.19.1       |
| Node     | v8.12.0       |
| OS       | mac |

## Input

```pug
input(placeholder="{{:: 'some.token.to.translate' | translate}}")
```

## Output or Error

```bash
["ERROR" - 2:02:53 PM] Error formatting document.
["ERROR" - 2:02:53 PM] Unhandled token: {"type":"attribute","loc":{"start":{"line":1,"column":7},"end":{"line":1,"column":65}},"name":"placeholder","val":"\"{{:: 'some.token.to.translate' | translate}}\"","mustEscape":true}
Error: Unhandled token: {"type":"attribute","loc":{"start":{"line":1,"column":7},"end":{"line":1,"column":65}},"name":"placeholder","val":"\"{{:: 'some.token.to.translate' | translate}}\"","mustEscape":true}
	at PugPrinter.build (redacted/node_modules/@prettier/plugin-pug/dist/printer.js:78:23)
	at Object.print (redacted/node_modules/@prettier/plugin-pug/dist/index.js:63:40)
	at callPluginPrintFunction (redacted/node_modules/prettier/index.js:12984:18)
	at redacted/node_modules/prettier/index.js:12935:16
	at Object.printComments (redacted/node_modules/prettier/index.js:12656:17)
	at printGenerically (redacted/node_modules/prettier/index.js:12934:22)
	at printAstToDoc (redacted/node_modules/prettier/index.js:12946:13)
	at coreFormat (redacted/node_modules/prettier/index.js:13265:13)
	at format (redacted/node_modules/prettier/index.js:13510:73)
	at formatWithCursor (redacted/node_modules/prettier/index.js:13526:12)
	at redacted/node_modules/prettier/index.js:44207:15
	at Object.format (redacted/node_modules/prettier/index.js:44226:12)
	at /Users/my.name/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:350954
	at t.default.safeExecution (/Users/my.name/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:351254)
	at t.default.<anonymous> (/Users/my.name/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:350934)
	at Generator.next (<anonymous>)
	at s (/Users/my.name/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:1:345019)
```

## Expected Output

```pug

```

## Additional Context
It looks like double colon (::) aka [one-time binding](https://docs.angularjs.org/guide/expression#one-time-binding) isn't recognized if it is used inside quotes because `p {{ :: 'some.token.to.translate' | translate }}` doesn't error and formats the document.

**Comment by Shinigami92** [comment]
Ohhhhhh I see, this is AngularJS, not Angular (2+) 😕
I'm using prettier internal functions to handle bindings, actions and expression for Angular and Vue... So it could be, that I cant support this kind of syntax 😞

It's this part:

https://github.com/prettier/plugin-pug/blob/aae29b8249e5c751ad906fd80920edf6b195be12/src/printer.ts#L510-L511

And this will run this part:

https://github.com/prettier/plugin-pug/blob/aae29b8249e5c751ad906fd80920edf6b195be12/src/printer.ts#L308-L311

So as you can see, I'm using `__ng_interpolation` and this is an internal parser of prettier core.

---

If you want to send a pull request for this issue, I'm open to review and check it.

**Comment by rromashka** [comment]
I have the same problem with pug und AngularJS

**Comment by Shinigami92** [comment]
@rromashka PRs are welcome, I'm willing to review

**Comment by Shinigami92** [comment]
If no one will create a PR for this I will close this issue on `December 31, 2021`  
That's the LTS date of AngularJS
